VELOCIDADE_DO_SOM_ESPERADA = 340.27 #(m/s)

# Oscilador (celular com phyphox)
FREQUENCIA_MINIMA_PHYPHOX = 10 #(Hz)
FREQUENCIA_MAXIMA_PHYPHOX = 10000 #(Hz)

# Experimento dos tubos
COMPRIMENTO_TUBO_PEQUENO = 0.225 #(m)
DIAMETRO_TUBO_PEQUENO = 0.037 #(m)
COMPRIMENTO_TUBO_GRANDE = 1.001 #(m)
DIAMETRO_TUBO_GRANDE = 0.037 #(m)
GRADACAO_DO_MEDIDOR_DE_COMPRIMENTO = 0.001 #(m)

# Experimento do Ressoador de Helmholtz
COMPRIMENTO_GARGALO = 0.100 #(m)
DIAMETRO_GARGALO = 0.025 #(m)
VOLUME_DO_RESSOADOR = 0.000750 #(m**3)
GRADACAO_DO_MEDIDOR_DE_VOLUME = 0.000050 #(m**3)
